# eureka-server (Service 필수)
apiVersion: v1
kind: Service
metadata:
  name: hexagon-cartpost-service
spec:
  selector:
    app: hexagon-cartpost-service
  ports:
    - port: 8081
      targetPort: 8081