# eureka-server (Service 필수)
apiVersion: v1
kind: Service
metadata:
  name: hexagon-communication-service
spec:
  selector:
    app: hexagon-communication-service
  ports:
    - port: 8082
      targetPort: 8082