apiVersion: v1

kind: Service

metadata:
  name: kafka

spec:

  selector:
    app: kafka

  ports:
    - name: plaintext
      targetPort: 9090
      port: 9090
    - name: controller
      targetPort: 9091
      port: 9091
    - name: external
      targetPort: 9092
      port: 9092