apiVersion: v1

kind: ConfigMap

metadata:
  name: kafka-config-map

data:
  KAFKA_NODE_ID: "1"
  CLUSTER_ID: "ZWU1Y2JiNDctNDg3ZC0tNGY2Ny1iNzJh"
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"
  KAFKA_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9090,EXTERNAL://kafka:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"