apiVersion: v1

kind: ConfigMap

metadata:
  name: kafka-config-map

data:
  KAFKA_NODE_ID: "1"
  CLUSTER_ID: "ZWU1Y2JiNDctNDg3ZC0tNGY2Ny1iNzJh"
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"  # ← Service 이름 그대로 사용
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9091"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"  # ← Service 이름
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"  # PVC 마운트 경로